version: '3'

services:
  web:
    build: ./web
    volumes:
     - ./web/www:/var/www
     - ./web/logs:/var/log
    ports:
      - 80:80
  
  cgi:
    build: ./cgi
    ports:
      - 8080:80
    depends_on:
      - web

  rest:
    build: ./rest
    ports:
      - 1337:80
    depends_on:
      - cgi
