version: '3'

services:
  web:
    build: ./web
    volumes:
     - ./web/www:/var/www
     - ./web/logs:/var/log
    ports:
      - 80:80
  
  cgi:
    build: ./cgi
    volumes:
     - ./cgi/cgi:/usr/local/apache2/cgi-bin/
     - ./cgi/html:/usr/local/apache2/html/
    ports:
      - 8080:80
    depends_on:
      - web

  rest:
    build: ./rest
    volumes:
     - ./rest/db:/db/
    ports:
      - 1337:1337
    depends_on:
      - cgi
